packages:
    - packages/types
    - packages/errors
    - packages/utils
    - packages/db
    - packages/global-configs
    - packages/shared-modules
    - packages/zod-schemas
    - packages/sdk/api
    - services/api
    - services/tgbot
    - services/worker
    - services/client

