import express, { Router } from "express";
import swaggerUi from "swagger-ui-express";

import { swaggerSpec } from "@/src/server/common/api-docs/swagger";
import { generateOpenAPIDocument } from "@/src/server/common/api-docs/openAPI";
import { combinedSwaggerSpec } from "@/src/server/common/api-docs";

const router: Router = express.Router();

// SwaggerJS documentation
router.use("/api", swaggerUi.serve, swaggerUi.setup(swaggerSpec));
// OpenAPI autogenerated documentation
router.use("/auto", swaggerUi.serve, swaggerUi.setup(generateOpenAPIDocument()))
// Combined
router.use("/combined", swaggerUi.serve, swaggerUi.setup(combinedSwaggerSpec))

router.get("/swagger.json", (_req: express.Request, res: express.Response) => {
    res.setHeader("Content-Type", "application/json");
    res.send(generateOpenAPIDocument());
});


export default router
