/* tslint:disable */
/* eslint-disable */
/**
 * Api Swagger
 * API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
/**
 * TONConnectApi - axios parameter creator
 * @export
 */
export const TONConnectApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Send proof for validation
         * @summary Send proof
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tonConnectCheckProofPost: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/ton-connect/check-proof`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Get payload for proof generation
         * @summary Payload for proof generation
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tonConnectGeneratePayloadPost: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/ton-connect/generate-payload`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * TONConnect Manifest file
         * @summary TONConnect manifest.json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tonConnectManifestJsonGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/ton-connect/manifest.json`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TONConnectApi - functional programming interface
 * @export
 */
export const TONConnectApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Send proof for validation
         * @summary Send proof
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async tonConnectCheckProofPost(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await TONConnectApiAxiosParamCreator(configuration).tonConnectCheckProofPost(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Get payload for proof generation
         * @summary Payload for proof generation
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async tonConnectGeneratePayloadPost(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await TONConnectApiAxiosParamCreator(configuration).tonConnectGeneratePayloadPost(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * TONConnect Manifest file
         * @summary TONConnect manifest.json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async tonConnectManifestJsonGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await TONConnectApiAxiosParamCreator(configuration).tonConnectManifestJsonGet(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * TONConnectApi - factory interface
 * @export
 */
export const TONConnectApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Send proof for validation
         * @summary Send proof
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async tonConnectCheckProofPost(options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return TONConnectApiFp(configuration).tonConnectCheckProofPost(options).then((request) => request(axios, basePath));
        },
        /**
         * Get payload for proof generation
         * @summary Payload for proof generation
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async tonConnectGeneratePayloadPost(options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return TONConnectApiFp(configuration).tonConnectGeneratePayloadPost(options).then((request) => request(axios, basePath));
        },
        /**
         * TONConnect Manifest file
         * @summary TONConnect manifest.json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async tonConnectManifestJsonGet(options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return TONConnectApiFp(configuration).tonConnectManifestJsonGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TONConnectApi - object-oriented interface
 * @export
 * @class TONConnectApi
 * @extends {BaseAPI}
 */
export class TONConnectApi extends BaseAPI {
    /**
     * Send proof for validation
     * @summary Send proof
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TONConnectApi
     */
    public async tonConnectCheckProofPost(options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return TONConnectApiFp(this.configuration).tonConnectCheckProofPost(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Get payload for proof generation
     * @summary Payload for proof generation
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TONConnectApi
     */
    public async tonConnectGeneratePayloadPost(options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return TONConnectApiFp(this.configuration).tonConnectGeneratePayloadPost(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * TONConnect Manifest file
     * @summary TONConnect manifest.json
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TONConnectApi
     */
    public async tonConnectManifestJsonGet(options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return TONConnectApiFp(this.configuration).tonConnectManifestJsonGet(options).then((request) => request(this.axios, this.basePath));
    }
}
