/* tslint:disable */
/* eslint-disable */
/**
 * Api Swagger
 * API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse400Data
 */
export interface InlineResponse400Data {

    /**
     * @type {number}
     * @memberof InlineResponse400Data
     * @example 1212
     */
    statusCode: number;
}
