/* tslint:disable */
/* eslint-disable */
/**
 * Api Swagger
 * API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InlineResponse400Data } from './inline-response400-data';
 /**
 * Validation failure
 *
 * @export
 * @interface InlineResponse400
 */
export interface InlineResponse400 {

    /**
     * @type {boolean}
     * @memberof InlineResponse400
     * @example false
     */
    success?: boolean;

    /**
     * @type {number}
     * @memberof InlineResponse400
     * @example 400
     */
    statusCode?: number;

    /**
     * Service response code. May missmatch http-code. See service error definitions.
     *
     * @type {string}
     * @memberof InlineResponse400
     * @example 200
     */
    code?: string;

    /**
     * Error message that shown to user
     *
     * @type {string}
     * @memberof InlineResponse400
     * @example Error message
     */
    message?: string;

    /**
     * @type {InlineResponse400Data}
     * @memberof InlineResponse400
     */
    data?: InlineResponse400Data;
}
