/* tslint:disable */
/* eslint-disable */
/**
 * Api Swagger
 * API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface PaginationRequestSchema
 */
export interface PaginationRequestSchema {

    /**
     * The number of items to retrieve per page
     *
     * @type {number}
     * @memberof PaginationRequestSchema
     */
    take?: number;

    /**
     * The page number to retrieve
     *
     * @type {number}
     * @memberof PaginationRequestSchema
     */
    page?: number;

    /**
     * The order in which to sort the leaderboard
     *
     * @type {string}
     * @memberof PaginationRequestSchema
     */
    sortOrder?: PaginationRequestSchemaSortOrderEnum;

    /**
     * @type {string}
     * @memberof PaginationRequestSchema
     */
    search?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum PaginationRequestSchemaSortOrderEnum {
    ASC = 'ASC',
    DESC = 'DESC'
}

