/* tslint:disable */
/* eslint-disable */
/**
 * Api Swagger
 * API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface RegisterRequest
 */
export interface RegisterRequest {

    /**
     * User's first name
     *
     * @type {string}
     * @memberof RegisterRequest
     * @example John
     */
    firstName: string;

    /**
     * User's last name
     *
     * @type {string}
     * @memberof RegisterRequest
     * @example Doe
     */
    lastName: string;

    /**
     * User's email address
     *
     * @type {string}
     * @memberof RegisterRequest
     * @example john.doe@example.com
     */
    email: string;

    /**
     * User's phone number
     *
     * @type {string}
     * @memberof RegisterRequest
     * @example +1234567890
     */
    phoneNumber: string;

    /**
     * User's password
     *
     * @type {string}
     * @memberof RegisterRequest
     */
    password: string;

    /**
     * Password confirmation
     *
     * @type {string}
     * @memberof RegisterRequest
     */
    confirmPassword: string;

    /**
     * User must accept terms and privacy policy
     *
     * @type {boolean}
     * @memberof RegisterRequest
     * @example true
     */
    termsAccepted: boolean;

    /**
     * CAPTCHA verification token
     *
     * @type {string}
     * @memberof RegisterRequest
     */
    captchaToken: string;
}
