import { MigrationInterface, QueryRunner } from "typeorm";

export class ZRP1744995244707 implements MigrationInterface {
    name = 'ZRP1744995244707'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "roles_to_actions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "action_id" uuid NOT NULL, "role_id" uuid NOT NULL, "enabled" boolean DEFAULT false, CONSTRAINT "PK_4c82b6e1b333cd90ec5e01f8621" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "actions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" character varying(64) NOT NULL DEFAULT 'system', "name" character varying(128) NOT NULL, "description" character varying(256), "enabled" boolean NOT NULL DEFAULT true, CONSTRAINT "actions_name_type_constraint" UNIQUE ("type", "name"), CONSTRAINT "PK_7bfb822f56be449c0b8adbf83cf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cities" ("id" SERIAL NOT NULL, "external_id" integer, "name" character varying(255), "state_id" integer, "latitude" numeric, "longitude" numeric, "wiki_data_id" character varying(255), "country_code" character varying(255), "state_code" character varying(255), "country_id" integer, CONSTRAINT "UQ_d5f0fb4d859ea004ffe39d7bf3a" UNIQUE ("external_id"), CONSTRAINT "PK_4762ffb6e5d198cfec5606bc11e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "cities_external_id_key" ON "cities" ("external_id") `);
        await queryRunner.query(`CREATE TABLE "currencies" ("id" SERIAL NOT NULL, "code" character varying(3) NOT NULL, "name" character varying(255), "symbol" character varying(10), "minor_unit" integer, "exchange_rate" numeric(20,10), "active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_d528c54860c4182db13548e08c4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "languages" ("id" SERIAL NOT NULL, "name" character varying(255), "native_name" character varying(255), "emoji" character varying(255), "emojiu" character varying(255), "code" character varying(255), CONSTRAINT "PK_b517f827ca496b29f4d549c631d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "countries" ("id" SERIAL NOT NULL, "external_id" integer, "name" character varying(255), "iso3" character varying(31), "iso2" character varying(31), "numeric_code" character varying(31), "capital" character varying(255), "currency_symbol" character varying(255), "tld" character varying(31), "native" character varying(255), "region" character varying(255), "subregion" character varying(255), "timezones" jsonb, "latitude" numeric, "longitude" numeric, "emoji" character varying(63), "emojiu" character varying(63), "phone_code" character varying(31), "currency_id" integer, "language_id" integer, CONSTRAINT "UQ_b53823b4a41611fd779408c2a49" UNIQUE ("external_id"), CONSTRAINT "PK_b2d7006793e8697ab3ae2deff18" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "countries_external_id_key" ON "countries" ("external_id") `);
        await queryRunner.query(`CREATE TABLE "company_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255), "director_name" character varying(255), "address" character varying(1024), "email" character varying(255), "url" character varying(255), "phone" character varying(255), "county_id" integer, CONSTRAINT "PK_1980200b310bd1e2ac86aa1ae4a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "companies_to_users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "company_id" uuid NOT NULL, "user_id" uuid NOT NULL, CONSTRAINT "PK_1a813bbae0949b76fe24ad087dc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_3bd36b405f5bc3f7730e1164e7" ON "companies_to_users" ("user_id", "company_id") `);
        await queryRunner.query(`CREATE TABLE "companies" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fb_id" character varying(255), "namespace" character varying(255), "status" character varying NOT NULL, "balance" numeric(18,8) DEFAULT '0', "currency_id" integer, "profile_id" uuid, CONSTRAINT "PK_d4bc3e82a314fa9e29f652c2c22" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(128) NOT NULL, "description" text, "company_id" uuid, CONSTRAINT "companies_company_name_constraint" UNIQUE ("company_id", "name"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users_to_roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "role_id" uuid NOT NULL, CONSTRAINT "PK_aa3128fef1162a328ac283c6cc3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_3c5401b4b6598b480175395e36" ON "users_to_roles" ("user_id", "role_id") `);
        await queryRunner.query(`CREATE TABLE "files" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "location" character varying, "s3" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "updated_at" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "type" character varying(64), "name" character varying, "original_name" character varying, "sourceUrl" character varying, "extension" character varying(255), "mimetype" character varying(255), "checksum" character varying(1024), "meta" jsonb, "purgeable" boolean NOT NULL DEFAULT false, "size" bigint, "encryption" character varying(64), "encrypted" boolean DEFAULT false, "purgable" boolean DEFAULT false, "checked" boolean DEFAULT false, "user_id" uuid, CONSTRAINT "PK_6c16b9093a142e0e7613b04a3d9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "files_checksum_user_key" ON "files" ("checksum", "user_id") `);
        await queryRunner.query(`CREATE TABLE "users" ("created_at" TIMESTAMP DEFAULT ('now'::text)::timestamp(6) with time zone, "updated_at" TIMESTAMP DEFAULT ('now'::text)::timestamp(6) with time zone, "deleted_at" TIMESTAMP, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "phone" character varying(255), "email" character varying, "status" character varying NOT NULL DEFAULT 'new', "last_seen" TIMESTAMP, "on_boarding_complete" boolean NOT NULL DEFAULT false, "active_session_address_id" uuid, "language" character varying(64) DEFAULT 'en', "country_id" integer, "profile_image" uuid, CONSTRAINT "REL_7aabff5209030c641ad4691024" UNIQUE ("active_session_address_id"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_users_id" ON "users" ("id") `);
        await queryRunner.query(`CREATE INDEX "idx_users_active_session_address_id" ON "users" ("active_session_address_id") `);
        await queryRunner.query(`CREATE TABLE "auth_tokens" ("created_at" TIMESTAMP DEFAULT ('now'::text)::timestamp(6) with time zone, "updated_at" TIMESTAMP DEFAULT ('now'::text)::timestamp(6) with time zone, "deleted_at" TIMESTAMP, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" character varying(255) DEFAULT 'api_token', "name" character varying(255), "description" text, "isActive" boolean NOT NULL DEFAULT true, "hash" text NOT NULL, "validUntil" TIMESTAMP, "lastUsedAt" TIMESTAMP, "userId" uuid, CONSTRAINT "PK_41e9ddfbb32da18c4e85e45c2fd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "addresses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "address" character varying NOT NULL, "public_key" character varying, "format" character varying, "encoding" character varying, "type" character varying, "last_sync" TIMESTAMP DEFAULT now(), "user_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "updated_at" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, CONSTRAINT "UQ_69b31ba33682e27f43b4754126a" UNIQUE ("address"), CONSTRAINT "PK_745d8f43d3af10ab8247465e450" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_addresses_user_id" ON "addresses" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "tg_chats" ("id" bigint NOT NULL, "language" character varying DEFAULT 'en', "title" character varying, "type" character varying, "status" character varying DEFAULT 'registerd', "created_at" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "updated_at" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "tg_user_id" bigint, CONSTRAINT "UQ_ee367626063761bd9e3abf5fccf" UNIQUE ("id"), CONSTRAINT "PK_ee367626063761bd9e3abf5fccf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "tg_chats_pkey" ON "tg_chats" ("id") `);
        await queryRunner.query(`CREATE TABLE "tg_users" ("id" bigint NOT NULL, "is_bot" boolean NOT NULL DEFAULT false, "first_name" character varying, "last_name" character varying, "username" character varying, "type" character varying DEFAULT 'user', "language" character varying DEFAULT 'en', "status" character varying DEFAULT 'registerd', "created_at" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "updated_at" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "user_id" uuid NOT NULL, "referrer_id" bigint, CONSTRAINT "UQ_9ca7cb460931bb8da0685e39fc8" UNIQUE ("id"), CONSTRAINT "REL_d7504ce684bf53b9e05140b051" UNIQUE ("user_id"), CONSTRAINT "PK_9ca7cb460931bb8da0685e39fc8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_tg_users_user_id" ON "tg_users" ("user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "tg_users_pkey" ON "tg_users" ("id") `);
        await queryRunner.query(`CREATE TABLE "tg_update" ("id" bigint NOT NULL, "type" character varying, "tg_message_id" bigint, CONSTRAINT "UQ_c0928aae6851aecc6f944dd0de2" UNIQUE ("id"), CONSTRAINT "PK_c0928aae6851aecc6f944dd0de2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "tg_update_pkey" ON "tg_update" ("id") `);
        await queryRunner.query(`CREATE TABLE "tg_messages" ("id" bigint NOT NULL, "date" TIMESTAMP DEFAULT now(), "raw" jsonb, "text" character varying, "type" character varying DEFAULT 'user', "tg_user_id" bigint, "tg_chat_id" bigint, CONSTRAINT "UQ_328dacf9f7956030249e97a8f73" UNIQUE ("id"), CONSTRAINT "PK_328dacf9f7956030249e97a8f73" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "tg_messages_pkey" ON "tg_messages" ("id") `);
        await queryRunner.query(`CREATE TABLE "ton_connect_sessions" ("user_id" uuid NOT NULL, "key" character varying NOT NULL, "session" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "updated_at" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, CONSTRAINT "ton_connect_sessions__user_id__key_qkey" UNIQUE ("user_id", "key"), CONSTRAINT "PK_f5593308dbe92e1bc9fed124dd0" PRIMARY KEY ("user_id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "ton_connect_sessions_pkey" ON "ton_connect_sessions" ("user_id") `);
        await queryRunner.query(`ALTER TABLE "roles_to_actions" ADD CONSTRAINT "fk_roles_to_actions_role_id" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "roles_to_actions" ADD CONSTRAINT "fk_roles_to_actions_action_id" FOREIGN KEY ("action_id") REFERENCES "actions"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "cities" ADD CONSTRAINT "FK_4aa0d9a52c36ff93415934e2d2b" FOREIGN KEY ("country_id") REFERENCES "countries"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "countries" ADD CONSTRAINT "FK_dbc8b7c7ea68824c33bc3c1e6f4" FOREIGN KEY ("currency_id") REFERENCES "currencies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "countries" ADD CONSTRAINT "FK_29aa6ca83c2f94df3cb765c35f1" FOREIGN KEY ("language_id") REFERENCES "languages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "company_profiles" ADD CONSTRAINT "FK_f429960cdd33e9dec25ee28e533" FOREIGN KEY ("county_id") REFERENCES "countries"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "companies_to_users" ADD CONSTRAINT "fk_companies_to_users_company_id" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "companies_to_users" ADD CONSTRAINT "fk_companies_to_users_user_id" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "companies" ADD CONSTRAINT "FK_88b5afdd4718044876d5508038f" FOREIGN KEY ("currency_id") REFERENCES "currencies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "companies" ADD CONSTRAINT "FK_9e1715d95eb53431a2e79bcf270" FOREIGN KEY ("profile_id") REFERENCES "company_profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "roles" ADD CONSTRAINT "FK_4bc1204a05dde26383e3955b0a1" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "users_to_roles" ADD CONSTRAINT "fk_users_to_roles_user_id" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "users_to_roles" ADD CONSTRAINT "fk_users_to_roles_role_id" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "files" ADD CONSTRAINT "FK_a7435dbb7583938d5e7d1376041" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "fk_active_session_address" FOREIGN KEY ("active_session_address_id") REFERENCES "addresses"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_ae78dc6cb10aa14cfef96b2dd90" FOREIGN KEY ("country_id") REFERENCES "countries"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_b942413feef0a5cd9af7c4841dd" FOREIGN KEY ("profile_image") REFERENCES "files"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth_tokens" ADD CONSTRAINT "FK_c25fb956ebada4b256501585cca" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "addresses" ADD CONSTRAINT "FK_16aac8a9f6f9c1dd6bcb75ec023" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "tg_chats" ADD CONSTRAINT "FK_14b9b880a82d817002f17b489e7" FOREIGN KEY ("tg_user_id") REFERENCES "tg_users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "tg_users" ADD CONSTRAINT "fk_tg_users_users_id" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "tg_users" ADD CONSTRAINT "fk_tg_users_referrer_id" FOREIGN KEY ("referrer_id") REFERENCES "tg_users"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "tg_update" ADD CONSTRAINT "FK_1215ea073bca508788e878df307" FOREIGN KEY ("tg_message_id") REFERENCES "tg_messages"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "tg_messages" ADD CONSTRAINT "FK_1e184dd38aafbd884c895a748ac" FOREIGN KEY ("tg_user_id") REFERENCES "tg_users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "tg_messages" ADD CONSTRAINT "FK_e3d36ccd2ce571965b44c5b08fb" FOREIGN KEY ("tg_chat_id") REFERENCES "tg_chats"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "ton_connect_sessions" ADD CONSTRAINT "FK_f5593308dbe92e1bc9fed124dd0" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "ton_connect_sessions" DROP CONSTRAINT "FK_f5593308dbe92e1bc9fed124dd0"`);
        await queryRunner.query(`ALTER TABLE "tg_messages" DROP CONSTRAINT "FK_e3d36ccd2ce571965b44c5b08fb"`);
        await queryRunner.query(`ALTER TABLE "tg_messages" DROP CONSTRAINT "FK_1e184dd38aafbd884c895a748ac"`);
        await queryRunner.query(`ALTER TABLE "tg_update" DROP CONSTRAINT "FK_1215ea073bca508788e878df307"`);
        await queryRunner.query(`ALTER TABLE "tg_users" DROP CONSTRAINT "fk_tg_users_referrer_id"`);
        await queryRunner.query(`ALTER TABLE "tg_users" DROP CONSTRAINT "fk_tg_users_users_id"`);
        await queryRunner.query(`ALTER TABLE "tg_chats" DROP CONSTRAINT "FK_14b9b880a82d817002f17b489e7"`);
        await queryRunner.query(`ALTER TABLE "addresses" DROP CONSTRAINT "FK_16aac8a9f6f9c1dd6bcb75ec023"`);
        await queryRunner.query(`ALTER TABLE "auth_tokens" DROP CONSTRAINT "FK_c25fb956ebada4b256501585cca"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_b942413feef0a5cd9af7c4841dd"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_ae78dc6cb10aa14cfef96b2dd90"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "fk_active_session_address"`);
        await queryRunner.query(`ALTER TABLE "files" DROP CONSTRAINT "FK_a7435dbb7583938d5e7d1376041"`);
        await queryRunner.query(`ALTER TABLE "users_to_roles" DROP CONSTRAINT "fk_users_to_roles_role_id"`);
        await queryRunner.query(`ALTER TABLE "users_to_roles" DROP CONSTRAINT "fk_users_to_roles_user_id"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP CONSTRAINT "FK_4bc1204a05dde26383e3955b0a1"`);
        await queryRunner.query(`ALTER TABLE "companies" DROP CONSTRAINT "FK_9e1715d95eb53431a2e79bcf270"`);
        await queryRunner.query(`ALTER TABLE "companies" DROP CONSTRAINT "FK_88b5afdd4718044876d5508038f"`);
        await queryRunner.query(`ALTER TABLE "companies_to_users" DROP CONSTRAINT "fk_companies_to_users_user_id"`);
        await queryRunner.query(`ALTER TABLE "companies_to_users" DROP CONSTRAINT "fk_companies_to_users_company_id"`);
        await queryRunner.query(`ALTER TABLE "company_profiles" DROP CONSTRAINT "FK_f429960cdd33e9dec25ee28e533"`);
        await queryRunner.query(`ALTER TABLE "countries" DROP CONSTRAINT "FK_29aa6ca83c2f94df3cb765c35f1"`);
        await queryRunner.query(`ALTER TABLE "countries" DROP CONSTRAINT "FK_dbc8b7c7ea68824c33bc3c1e6f4"`);
        await queryRunner.query(`ALTER TABLE "cities" DROP CONSTRAINT "FK_4aa0d9a52c36ff93415934e2d2b"`);
        await queryRunner.query(`ALTER TABLE "roles_to_actions" DROP CONSTRAINT "fk_roles_to_actions_action_id"`);
        await queryRunner.query(`ALTER TABLE "roles_to_actions" DROP CONSTRAINT "fk_roles_to_actions_role_id"`);
        await queryRunner.query(`DROP INDEX "public"."ton_connect_sessions_pkey"`);
        await queryRunner.query(`DROP TABLE "ton_connect_sessions"`);
        await queryRunner.query(`DROP INDEX "public"."tg_messages_pkey"`);
        await queryRunner.query(`DROP TABLE "tg_messages"`);
        await queryRunner.query(`DROP INDEX "public"."tg_update_pkey"`);
        await queryRunner.query(`DROP TABLE "tg_update"`);
        await queryRunner.query(`DROP INDEX "public"."tg_users_pkey"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tg_users_user_id"`);
        await queryRunner.query(`DROP TABLE "tg_users"`);
        await queryRunner.query(`DROP INDEX "public"."tg_chats_pkey"`);
        await queryRunner.query(`DROP TABLE "tg_chats"`);
        await queryRunner.query(`DROP INDEX "public"."idx_addresses_user_id"`);
        await queryRunner.query(`DROP TABLE "addresses"`);
        await queryRunner.query(`DROP TABLE "auth_tokens"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_active_session_address_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_id"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP INDEX "public"."files_checksum_user_key"`);
        await queryRunner.query(`DROP TABLE "files"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3c5401b4b6598b480175395e36"`);
        await queryRunner.query(`DROP TABLE "users_to_roles"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TABLE "companies"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3bd36b405f5bc3f7730e1164e7"`);
        await queryRunner.query(`DROP TABLE "companies_to_users"`);
        await queryRunner.query(`DROP TABLE "company_profiles"`);
        await queryRunner.query(`DROP INDEX "public"."countries_external_id_key"`);
        await queryRunner.query(`DROP TABLE "countries"`);
        await queryRunner.query(`DROP TABLE "languages"`);
        await queryRunner.query(`DROP TABLE "currencies"`);
        await queryRunner.query(`DROP INDEX "public"."cities_external_id_key"`);
        await queryRunner.query(`DROP TABLE "cities"`);
        await queryRunner.query(`DROP TABLE "actions"`);
        await queryRunner.query(`DROP TABLE "roles_to_actions"`);
    }

}
