import express, { Router } from "express";
import swaggerUi from "swagger-ui-express";

import {
    swaggerSpec,
    generateOpenAPIDocument,
    combineSwaggerAndOpenAPIDocuments,
} from "../../common";


export function generateDocsRouter() {
    const router: Router = express.Router();

    // SwaggerJS documentation
    router.use("/api", swaggerUi.serve, swaggerUi.setup(swaggerSpec));
    // OpenAPI autogenerated documentation
    router.use("/auto", swaggerUi.serve, swaggerUi.setup(generateOpenAPIDocument()));
    // Combined
    router.use("/combined", swaggerUi.serve, swaggerUi.setup(combineSwaggerAndOpenAPIDocuments()));

    router.get("/swagger.json", (_req: express.Request, res: express.Response) => {
        res.setHeader("Content-Type", "application/json");
        res.send(generateOpenAPIDocument());
    });
    return router;
}
