/* tslint:disable */
/* eslint-disable */
/**
 * Api Swagger
 * API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Authenticated
 *
 * @export
 * @interface InlineResponse2001
 */
export interface InlineResponse2001 {

    /**
     * @type {boolean}
     * @memberof InlineResponse2001
     * @example true
     */
    success?: boolean;

    /**
     * @type {number}
     * @memberof InlineResponse2001
     * @example 200
     */
    statusCode?: number;

    /**
     * Service response code. May missmatch http-code. See service error definitions.
     *
     * @type {string}
     * @memberof InlineResponse2001
     * @example 200
     */
    code?: string;

    /**
     * Error message that shown to user
     *
     * @type {string}
     * @memberof InlineResponse2001
     * @example Error message
     */
    message?: string;

    /**
     * @type {any}
     * @memberof InlineResponse2001
     */
    data?: any;
}
