/* tslint:disable */
/* eslint-disable */
/**
 * Api Swagger
 * API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface PaginationResponseSchema
 */
export interface PaginationResponseSchema {

    /**
     * Total number of items available
     *
     * @type {number}
     * @memberof PaginationResponseSchema
     * @example 100
     */
    count: number;

    /**
     * The current page number
     *
     * @type {number}
     * @memberof PaginationResponseSchema
     * @example 1
     */
    currentPage: number;

    /**
     * Next page number, if available
     *
     * @type {number}
     * @memberof PaginationResponseSchema
     * @example 2
     */
    nextPage: number | null;

    /**
     * Previous page number, if available
     *
     * @type {number}
     * @memberof PaginationResponseSchema
     */
    prevPage: number | null;

    /**
     * The last available page number
     *
     * @type {number}
     * @memberof PaginationResponseSchema
     * @example 10
     */
    lastPage: number;
}
